# Logo
logo_image_source: http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/assets/anodyne.svg

# Index Page
index_banner_text: BJ-Kim 개발블로그
index_banner_text_secondary: 반갑습니다!
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Contact: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://tachyons.io/img/avatar_1.jpg
about_widget_text: "김범준 입니다.<br>반갑습니다."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: bj-kim-1

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://twitter.com/?lang=en
    fa_icon: fa-twitter
  - url: https://www.facebook.com/
    fa_icon: fa-facebook
  - url: https://dribbble.com/
    fa_icon: fa-dribbble 
  - url: https://github.com/klugjo/hexo-theme-anodyne
    fa_icon: fa-github
  - url: https://plus.google.com/
    fa_icon: fa-google-plus
  - url: https://www.behance.net/
    fa_icon: fa-behance
  - url: https://500px.com/
    fa_icon: fa-500px
  - url: mailto:test@example.com
    fa_icon: fa-envelope
  - url: /#
    fa_icon: fa-rss

# Footer about
footer_about: ""
